name: Cancer_Prediction
channels:
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.8.0
  - pip:
    - -e .
    - aiohttp==3.8.4
    - aiohttp-retry==2.8.3
    - aiosignal==1.3.1
    - alembic==1.11.0
    - amqp==5.1.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - asyncssh==2.13.1
    - atpublic==3.1.1
    - attrs==23.1.0
    - billiard==3.6.4.0
    - blinker==1.6.2
    - celery==5.2.7
    - certifi==2023.5.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - cloudpickle==2.2.1
    - configobj==5.0.8
    - contourpy==1.0.7
    - cryptography==40.0.2
    - cycler==0.11.0
    - databricks-cli==0.17.7
    - dictdiffer==0.9.0
    - diskcache==5.6.1
    - distro==1.8.0
    - docker==6.1.2
    - dpath==2.1.5
    - dulwich==0.21.5
    - entrypoints==0.4
    - filelock==3.12.0
    - flask==2.3.2
    - flatten-dict==0.4.2
    - flufl-lock==7.1.1
    - fonttools==4.39.4
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - funcy==2.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - grandalf==0.8
    - greenlet==2.0.2
    - hydra-core==1.3.2
    - idna==3.4
    - importlib-resources==5.12.0
    - iterative-telemetry==0.0.8
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - kombu==5.2.4
    - mako==1.2.4
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mlflow==2.3.2
    - multidict==6.0.4
    - nanotime==0.5.2
    - networkx==3.1
    - numpy==1.24.3
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - orjson==3.8.12
    - pandas==2.0.1
    - pathspec==0.11.1
    - pillow==9.5.0
    - protobuf==4.23.0
    - pyarrow==11.0.0
    - pycparser==2.21
    - pydot==1.4.2
    - pygit2==1.12.1
    - pygtrie==2.5.0
    - pyjwt==2.7.0
    - pyparsing==3.0.9
    - pytz==2023.3
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - requests==2.30.0
    - rich==13.3.5
    - ruamel-yaml==0.17.26
    - ruamel-yaml-clib==0.2.7
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - scmrepo==1.0.3
    - seaborn==0.12.2
    - shortuuid==1.0.11
    - shtab==1.6.1
    - smmap==5.0.0
    - sqlalchemy==2.0.13
    - sqlparse==0.4.4
    - sqltrie==0.3.1
    - tabulate==0.9.0
    - threadpoolctl==3.1.0
    - tomlkit==0.11.8
    - tqdm==4.65.0
    - tzdata==2023.3
    - urllib3==1.26.15
    - vine==5.0.0
    - voluptuous==0.13.1
    - waitress==2.1.2
    - websocket-client==1.5.1
    - werkzeug==2.3.4
    - yarl==1.9.2
    - zc-lockfile==3.0.post1

