
ARTIFACTS:
  ARTIFACTS_PATH: artifacts
  TRAIN_LOADER_BIN : train_data.bin
  TEST_LOADER_BIN: test_data.bin
  SCALER_BIN: standard_scaler.pkl


SOURCE_DATA_DIRS:
  DIR: data
  FILENAME: Cancer_Data.csv

PARAMS:
  TRAIN_SPLIT_SIZE: 0.7
  COLS_TO_DROP : ["radius_mean",'perimeter_mean','area_mean','radius_worst', 
    'perimeter_worst','concave points_mean','concavity_mean', 
    'texture_worst','perimeter_se','radius_se']



